server:
  port: 8888
security:
  oauth2:
    resource:
      tokenInfoUri: http://localhost:8080/uaa/check_token
    client:
      clientId: oauth_showcase_authorization_code
      clientSecret: secret
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
spring:
  thymeleaf:
    cache: false
