server:
  port: 8888
spring:
  thymeleaf:
    cache: false
security:
  oauth2:
    client:
      client-id: oauth_showcase_authorization_code
      client-secret: secret
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/uaa/check_token
